global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sentinel-node'
    static_configs:
      - targets: ['sentinel-node:9090']
    metrics_path: /metrics

  - job_name: 'sentinel-brain'
    static_configs:
      - targets: ['sentinel-brain:50051']
    metrics_path: /metrics
